version: "3.8"

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  messenger:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env

  migrations:
    build: .
    entrypoint: [ "poetry", "run", "alembic" ]
    command: [ "upgrade", "head" ]
    depends_on:
      - postgres

volumes:
  postgres_data: